### ISSUE TITLE
Automatic layout of the generated code

### ISSUE THREAD

**Issue by AresEkb** [DevBoost/EMFText#66]
Hi

I'm using JaMoPP to generate Java-code. The problem is that the generated code is very ugly. It lacks spaces, newlines. Is there a simple way to add spaces into generated code? Or is there an automatic code formatter, which adds layout information according to some formatting rules?

Thanks!

**Comment by jjohannes** [comment]
Hi

JaMoPP does only a very simple layouting of the code. You could use another existing layouter after JaMoPP generated the code.

If you want to modify layout information manually: use the 'layoutInformation' reference each model element has. Here you can add spaces and newlines which will then be used during printing.

**Comment by AresEkb** [comment]
Thanks!
