### ISSUE TITLE
Compound keywords

### ISSUE THREAD

**Issue by AresEkb** [DevBoost/EMFText#68]
Hi

I have a following rule:

	Datatype.CharacterStringType ::=
		kind[ CHARACTER : "CHARACTER", CHAR : "CHAR", VARCHAR : "VARCHAR",
			CHARACTER_VARYING : "CHARACTER VARYING", CHAR_VARYING : "CHAR VARYING" ];

It works fine expect I can't insert extra spaces between "CHAR" and "VARYING".

I've changed my rule to

	Datatype.CharacterStringType ::=
		( kind[ CHARACTER : "CHARACTER", CHAR : "CHAR", VARCHAR : "VARCHAR" ]
		| kind[ CHARACTER_VARYING : "CHARACTER", CHAR_VARYING : "CHAR" ] "VARYING" );

Now I can insert extraspaces. But I get explicitSyntaxChoice warning (which I can suppress). And also autocomplete stops working. It autocompletes "CHAR" keyword, but it doesn't autocomplete "VARYING" keyword. I guess that such scenario is too complex for autocomplete... Could you suggest another solution for me?

I'm using EMFText 1.4.2.v201510080954

**Comment by mirkoseifert** [comment]
I think the second rule is a good way to go. From my experience, users of a DSL will not expect that only one space is allowed between "two" keywords.

Regarding the auto completion, this can be considered a bug.

**Comment by AresEkb** [comment]
Thanks for answer!

I'll use second variant. Maybe I'll debug completion algorithm, it's interesting how it works...
