### ISSUE TITLE
The code for the static initializer is exceeding the 65535 bytes limit	

### ISSUE THREAD

**Issue by flagadajones** [DevBoost/EMFText#74]
Hi,

I have a problem with my grammar, the Parser class have compilation problem: 

"The code for the static initializer is exceeding the 65535 bytes limit"

**Comment by mirkoseifert** [comment]
Can you provide your grammar and your metamodel to create a test case from that?

**Comment by flagadajones** [comment]
hi, 
sorry but i can't provide grammar.

For solve my problem i replace  
gramma like this :
```

"TRIM" "="  "("  trim ")"
by
"TRIM=("  trim ")"
```

to reduce static number
