### ISSUE TITLE
Wrong link to associateSites.xml inside update page

### ISSUE THREAD

**Issue by moerchtibroel** [DevBoost/EMFText#75]
There are wrong links to http://update.emftext.org/trunk/associateSites.xml on your official update page. The files http://update.emftext.org/trunk/site.xml and http://update.emftext.org/trunk/category.xml pointing to http://www.emftext.org/update_trunk/associateSites.xml. This causes errors in our mirror.

**Comment by cwende** [comment]
Thanks for the hint! I've fixed the urls.
