### ISSUE TITLE
CSV plugin

### ISSUE THREAD

**Issue by EmidioStani** [DevBoost/EMFText#77]
Hi,

I am interested in the CSV plugin:

http://www.emftext.org/index.php/EMFText_Concrete_Syntax_Zoo_CSV

but the links below do not work anymore, do you have the right link or  a copy of the files somewhere ? 

Thanks,

Emidio

**Comment by mirkoseifert** [comment]
See https://github.com/DevBoost/EMFText-Zoo/tree/master/Inhabitants/CSV
